development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:6508f870fe6192f5f161560b158408dd@pearlfish.redistogo.com:10291/
  channel_prefix: Mockering_production

